name: Deploy to Staging

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install # Replace with your package manager and install command if not using npm

    - name: Build and deploy to staging
      run: |
        # Replace the following command with your deployment script or commands
        npm run build
        ./deploy-to-staging.sh
